### ISSUE TITLE
Clicking on a project ignores teamcity http port

### ISSUE THREAD

**Issue by yamsellem** [erikdoe/ccmenu#31]
Say I add the `http://teamcity:8111/httpAuth/app/rest/cctray/projects.xml` url and choose some projects. In the project list, clicking on one of them will open `http://teamcity/viewType.html?buildTypeId=ProjectName_Target` in my browser, but without the `8111` port.

**Comment by erikdoe** [comment]
The behaviour you are seeing is caused by as misconfiguration of the TeamCity server you're trying to monitor. CCMenu simply opens the URL that is provided by the server: https://github.com/erikdoe/ccmenu/blob/6d65597097e1614881edc64f6814e9357dcec534/CCMenu/Classes/CCMStatusItemMenuController.m#L204-L206

Whoever is responsible for your TeamCity server has to look into why it's not providing the correct URLs, ie. URLs that contain the port. If your admins don't trust CCMenu, show them the raw XML for the feed, and it'll be obvious that the project URLs do not contain the port.
