### ISSUE TITLE
support for unstable builds (orange/yellow/amber)

### ISSUE THREAD

**Issue by ssbarnea** [erikdoe/ccmenu#52]
It seems that CCTray does not support the three colour states, where you do also have a yellow one that marks "unstable" build, usually ones the have a lower code-coverage.

For example we have code coverage alerts configured to mark builds as unstable if the coverage went down, but this can happen quite easily by rounding errors and now I see lots of "red"s which are in fact yellow-ish ones.

**Comment by erikdoe** [comment]
The problem is that the cctray format, which is used to communicate build states, does not support these states. Jenkins has no way of telling CCMenu anything other than green or red. To change this, the cctray format would have to be expanded, and the servers and utilities working with would have modified to support new states. This is something I'd love to see, but over many years there's never been any ownership or steering group for that cctray format.

**Comment by fkoehler** [comment]
I just checked a cc file and it contains the link to the job itself, i.e:

`<Project activity="Sleeping" lastBuildStatus="Failure" lastBuildLabel="250" webUrl="https://jenkins.xxx.de/job/somejob/" name="somename" lastBuildTime="2017-06-01T15:48:29Z"/>`

We could use that url to fetch more data via the REST api from jenkins, ie by adding `/api/json?pretty=true` to the URL (of course it needs to be activated and maybe authentication is needed). From there one can look at "color" or look at the latest build and check if it is unstable.

Would that be a feasible way to go?
