### ISSUE TITLE
integrate ccmenu with bamboo ci

### ISSUE THREAD

**Issue by ssbarnea** [erikdoe/ccmenu#55]
At this moment it seems that Atlassian Bamboo does not publish build status information using the cc.xml format, preferring to use their own format (as opposed to 99% of open-source and commercial build servers). 

There is a feature request for adding this at https://jira.atlassian.com/browse/BAM-2800 which is 8 years old. 

It seem far more likely to add support for Bamboo in CCMenu than pursuing Atlassian to implement it. 

I do encourage anyone, that want to see this fixed, to comment on Atlassian bug and to tweet about it using http://ctt.ec/885xz

**Comment by erikdoe** [comment]
This has been requested before, as early as 2009: https://sourceforge.net/p/ccmenu/feature-requests/7/

As I have stated at the time, I feel that this is not something that the CCMenu project should address. CCMenu is a tiny open source project, which a small number of people work on in their spare time. Bamboo is a commercial CI server backed by a well-funded company. Also, almost every CI server on the planet can produce a cctray.xml feed. It's not rocket science.

To be honest, even if somebody created a PR with special code to deal with Bamboo's feed, it'd be very unlikely that I'd accept the code. The reason is that from then on that code would become the responsibility of the CCMenu project, and we'd have to provide support for this feature, we'd have to refactor the code when something else changes, etc.

Unless somebody can bring up a compelling reason why Bamboo just cannot provide this feed, this will remain a _won't-fix_.

**Comment by ssbarnea** [comment]
Sadly, there is one reason for which I doubt Bamboo will do it: the ccxml format is very basic and allows only two states: failed and succeeded, with no way of showing a build that for example got lower code coverage.

I am not going to implement it myself because I am not really using Bamboo, I was only evaluating it and this missing feature was a good enough reason for cutting it from the list of possible alternatives to the ugly Jenkins.

**Comment by erikdoe** [comment]
So, the cctray format is extensible. If the Bamboo team extended it to introduce the concept of "not so great" builds, something that I believe Jenkins also has, and they provided a PR to CCMenu that could show this, that would be a different story...
