### ISSUE TITLE
Q: Where does CCMenu store it's configuration?

### ISSUE THREAD

**Issue by mdub** [erikdoe/ccmenu#62]
A change to our CI setup means I have to modify the URLs for _all_ my projects.  I'd rather not do that through the GUI, though.

I'm struggling to find a configuration file that I can edit. Help!

**Comment by erikdoe** [comment]
CCMenu uses the normal defaults mechanism to store its settings. The preferred way to access the defaults is via the `defaults` command line utility, e.g.

    defaults read net.sourceforge.cruisecontrol.ccmenu

The place where these are stored on disk is under Apple's control and has changed. Currently you should be able to find them here:

    ~/Library/Containers/net.sourceforge.cruisecontrol.CCMenu/Data/Library/Preferences/net.sourceforge.cruisecontrol.CCMenu.plist

When you modify the file you may have to log out and back in for the changes to come into effect. This is due to a caching mechanism introduced by Apple in OS X 10.9: http://hints.macworld.com/article.php?story=20130908042828630

There is an open enhancement request to switch to a configuration file (see #24).

**Comment by mrmanc** [comment]
Ended up here to work out how to change the hostname for our build server. After a bit of work, I came up with this way which uses `-` to direct `export` and `import` to use stdout/stdin so the defaults can be edited. This isn’t possible if you use the export to file option as the plist file format is binary.

```
defaults export -app CCMenu - | sed -e "s@http://old-host/cctray.xml@http://new-host/cctray.xml@g" | defaults import net.sourceforge.cruisecontrol.CCMenu -
```
