### ISSUE TITLE
After giving url and login no project is listed

### ISSUE THREAD

**Issue by dialex** [erikdoe/ccmenu#68]
Basically I followed the steps:

1. Get ready to configure CCMenu.
2. Paste the https://URL_TO_JENKINS_DOMAIN/cc.xml
3. Check **Requires login** and type login credentials.
4. Click confirm.

**Expected:** The projects screen lists the Jenkins' jobs.
**Actual:** The projects screens displays an empty list and I can't do anything about it.

On the URL I tried the `/cc.xml`, `/rssAll` and `/rssLatest`, none worked.
Am I doing something wrong?

**Comment by dialex** [comment]
I just remembered it, I think it's because my Jenkins environment requires a specific VPN to accept connections. Is this an issue? How can I workaround this?

**Comment by erikdoe** [comment]
With the information provided I can't say what the problem is. Please run the following command in Terminal (using the `cc.xml` URL and your username and password) and post the output here.

    curl -v -u username:password url

Please remember to obfuscate your username and password before posting the output. ;-)

**Comment by dialex** [comment]
Thanks for the command (and the tip about obfuscating) ;)

So it looks like it's not accepting my credentials. But I'm sure I'm using the right user/pass combination. And after login in on Jenkins I can open a new tab and access the `cc.xml` url.

```
curl -v -u USERNAME:PASS https://DOMAIN_URL/cc.xml
*   Trying 52.50.33.96...
* Connected to DOMAIN_URL (52.50.33.96) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: DOMAIN_URL
* Server auth using Basic with user 'USERNAME'
> GET /cc.xml HTTP/1.1
> Host: DOMAIN_URL
> Authorization: Basic ZG51bmVzOmRudW5lczE2X0ROVU5FUy12
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 401 Invalid password/token for user: USERNAME
< Server: nginx/1.8.1
< Date: Thu, 28 Jul 2016 12:58:06 GMT
< Content-Type: text/html;charset=ISO-8859-1
< Content-Length: 1431
< Connection: keep-alive
< X-Content-Type-Options: nosniff
* Authentication problem. Ignoring this.
< WWW-Authenticate: Basic realm="Jenkins"
< Cache-Control: must-revalidate,no-cache,no-store
<
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 401 Invalid password/token for user: USERNAME</title>
</head>
<body><h2>HTTP ERROR 401</h2>
<p>Problem accessing /cc.xml. Reason:
<pre>    Invalid password/token for user: USERNAME</pre></p><hr /><i><small>Powered by Jetty://</small></i><br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>

</body>
</html>
* Connection #0 to host DOMAIN_URL left intact
```

**Comment by erikdoe** [comment]
In case of Jenkins (and some other servers) the log in procedure for a normal user with a web browser is quite different from the authentication of the project status feeds. The user is shown an HTML form with username and password fields and the contents of the HTML form are sent to Jekins as form data. For the feeds, HTTP Basic Auth is used, which requires a special `Authorization` header on the request to the server. So, it is possible for one to work while the other one doesn't. In addition, Jenkins arguably doesn't implement authorization correctly, but CCMenu contains special code to deal with Jenkins.

With that said, to me it looks like you have an nginx in front of Jenkins, and it looks like nginx is dealing with the HTTP Basic Auth. It seems that the username/password you are transmitting are not valid for nginx and nginx then reports an authentication failure. Your login attempt on the web pages of Jenkins use HTML forms which nginx wouldn't touch.

At this stage I would suggest to talk to the people who are responsible for the servers you use. You can just show them the `curl` command that should work. Once they get this working CCMenu should work, too. I'm saying "should" because there's still one possible issue after `curl` works: if a server in front of Jenkins strips the `X-Jenkins` or `X-Hudson` headers then CCMenu doesn't know it's a Jenkins instance and it can't apply the special workaround for the incorrect Jenkins behaviour. Actually, CCMenu has yet another workaround for Cloudbees who do this, but for all others it relies on the headers. So, don't strip them!

**Comment by erikdoe** [comment]
Actually, the reason why CCMenu shows an empty list is most likely the following: nginx is stripping the `X-Jenkins` and `X-Hudson` headers, therefore CCMenu does not know it's Jenkins, it doesn't apply the workaround for Jenkins, and without the workaround, it seems to CCMenu that Jenkins doesn't have any projects.
