### ISSUE TITLE
Projects selection dialog is not scalable

### ISSUE THREAD

**Issue by birgitta410** [erikdoe/ccmenu#90]
It would be great if the selection window with the long list of projects could be scaled. (I currently cannot scale it, MacOS Sierra 10.12.6)

This is especially cumbersome for build servers with lots of nested projects that therefore have long paths/names, because the beginning of a lot of those paths is all the same and it makes it harder to find the project you're looking for when you cannot scale the width to see the whole path.

**Comment by jacksonjesse** [comment]
👍 to this, makes that window rather unusable on servers with lots of nesting!

**Comment by ssbarnea** [comment]
Maybe an image would clarify this issue. With current behaviour it is impossible to pick the right job from the list, because there is no way to pick the right one. No resize of scrolling is available.

<img width="429" alt="screen shot 2018-01-10 at 15 49 03" src="https://user-images.githubusercontent.com/102495/34781558-0d2e897e-f61e-11e7-83a1-f8dfce051c76.png">

**Comment by ssbarnea** [comment]
There is also an old PR that is supposed to address this issue also https://github.com/erikdoe/ccmenu/pull/87 -- but nobody bothered to review it.

**Comment by ssbarnea** [comment]
Guys, if you want this to ever be sorted please spend few minutes reviewing my PR above. Go to files > review and perform a review. This will probably help Eric making a decision regarding merging it.

**Comment by ssbarnea** [comment]
I can confirm that the current code from master is fixing this, so hopefully soon to see a new release.
